package com.idev4.compliance.dto;

public class LoanInfoDto {
	public String loanAppSeq;
	public String clntNm; 
	public String clntId;
	public String mrtlSts; 
	public String occ;
	public String cmntyNm; 
	public String portNm;
	public String odFlg; 
	public String prdSeq;
	public String nkinFlg; 
	public String bizChngFlg;
	public String clntAddr;
	public String resSts;
	public String resTnr; 
	public String totFmlyMemb;
	public String numOfErnrs; 
	public String prdNm;
	public String prevAmt; 
	public String loanCyclNum;
	public String rqstdLoanAmt; 
	public String aprvdLoanAmt;
	public String planNm; 
	public String scrnFlg;
	public String cnicNum; 
	public String cnicExpryDt;
	public String dob;
	public String gndr;
	public String bizActy;
	public String bizTnr; 
	public String bizAddr;
	public String bizIncm; 
	public String prsnRunBiz;
	public String prmIncm;
	public String secIncm;
	public String hsldExp;
	public String srvsChrg;
	public String pyblAmt;
	public String instNum;
	public String dsbmtDt;
	public String cmpltDt;
}
